name: Run Selenium Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.xlsx'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.xlsx'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal
